//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterNetworkProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaterNetworkProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string Consumer_Cancel {
            get {
                return ResourceManager.GetString("Consumer_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم المستخدم.
        /// </summary>
        public static string Consumer_FirstName {
            get {
                return ResourceManager.GetString("Consumer_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقب المستخدم.
        /// </summary>
        public static string Consumer_LastName {
            get {
                return ResourceManager.GetString("Consumer_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المستخدم.
        /// </summary>
        public static string Consumer_number {
            get {
                return ResourceManager.GetString("Consumer_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مستخدم.
        /// </summary>
        public static string Consumer_Register {
            get {
                return ResourceManager.GetString("Consumer_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ خلال أضافة المستخدم.
        /// </summary>
        public static string Consumers_AddConsumer_Error {
            get {
                return ResourceManager.GetString("Consumers_AddConsumer_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم أضافة المستخدم بنجاح.
        /// </summary>
        public static string Consumers_AddConsumer_Success {
            get {
                return ResourceManager.GetString("Consumers_AddConsumer_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم موجود مسبقا.
        /// </summary>
        public static string Consumers_ConsumerAlreadyExists {
            get {
                return ResourceManager.GetString("Consumers_ConsumerAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة المستخدمين.
        /// </summary>
        public static string Consumers_List {
            get {
                return ResourceManager.GetString("Consumers_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string Registration_Cancel {
            get {
                return ResourceManager.GetString("Registration_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قراءة العداد.
        /// </summary>
        public static string Registration_CounterLecture {
            get {
                return ResourceManager.GetString("Registration_CounterLecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ قراءة العداد.
        /// </summary>
        public static string Registration_Date {
            get {
                return ResourceManager.GetString("Registration_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة قراءة.
        /// </summary>
        public static string Registration_Make {
            get {
                return ResourceManager.GetString("Registration_Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل.
        /// </summary>
        public static string Registration_Register {
            get {
                return ResourceManager.GetString("Registration_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الفواتير.
        /// </summary>
        public static string Registrations_invoicesList {
            get {
                return ResourceManager.GetString("Registrations_invoicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما خلال التقييد.
        /// </summary>
        public static string Registrations_MakeRegistration_Error {
            get {
                return ResourceManager.GetString("Registrations_MakeRegistration_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التقييد بنجاح.
        /// </summary>
        public static string Registrations_MakeRegistration_Success {
            get {
                return ResourceManager.GetString("Registrations_MakeRegistration_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقييد موجود بالفعل.
        /// </summary>
        public static string Registrations_RegistrationAlreadyExists {
            get {
                return ResourceManager.GetString("Registrations_RegistrationAlreadyExists", resourceCulture);
            }
        }
    }
}
